### ISSUE TITLE
API call "Fetch all the triggered incidents" return just amount of incidents

### ISSUE THREAD

**Issue by petromamrai** [spikehq/community#20]
By description I do suppose to get list of incidents in state "triggered", but actually receive    just amount of incidents:
```
{
  "triggeredIncidents": 9
}
```

**Comment by ktkaushik** [comment]
Hi @petromamrai 

this was a valid issue. thanks for pointing out. We have fixed this and you should see it now.

Sorry, we are still setting this repo so couldn't respond earlier.
